version: '3.7'

services:
  db:
    image: postgres:14.7-alpine
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  db:
